import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import axios from "axios";
import styled from "styled-components";
import Main from "../components/Main";

export const Container = styled.div`
  grid-area: main;
  /* background-color: black; */
  /* margin-top: -100px; */
  margin-top: -100px;

  @media only screen and (max-width: 780px) {
    margin-top: -220px;
  }

  @media only screen and (min-width: 1400px) {
    margin-top: 100px;
  }

  @media only screen and (min-width: 1750px) {
    margin-top: 370px;
  }
`;

export const getServerSideProps = async (context) => {
  const resAction = await axios.get(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=28`
  );

  const resAdventure = await axios.get(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=12`
  );

  const resAnimation = await axios.get(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=16`
  );

  const resComedy = await axios.get(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=35`
  );

  const resCrime = await axios.get(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=80`
  );

  const resDocumentary = await axios.get(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=99`
  );

  const resDrama = await axios.get(
    `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=18`
  );

  const action = resAction.data.results;
  const adventure = resAdventure.data.results;
  const animation = resAnimation.data.results;
  const comedy = resComedy.data.results;
  const crime = resCrime.data.results;
  const documentary = resDocumentary.data.results;
  const drama = resDrama.data.results;

  let data = {
    action: action,
    adventure: adventure,
    animation: animation,
    comedy: comedy,
    crime: crime,
    documentary: documentary,
    drama: drama,
  };

  return {
    props: {
      // data: [],
      data: data,
    },
  };
};

export default function Home(data) {
  // useEffect(() => {
  //   const done = async () => {};
  //   done();
  // }, []);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main data={data.data}></Main>
    </Container>
  );
}
